/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/admin/Activities': RouteRecordInfo<'/admin/Activities', '/admin/Activities', Record<never, never>, Record<never, never>>,
    '/admin/Departments': RouteRecordInfo<'/admin/Departments', '/admin/Departments', Record<never, never>, Record<never, never>>,
    '/admin/Users': RouteRecordInfo<'/admin/Users', '/admin/Users', Record<never, never>, Record<never, never>>,
    '/Admin': RouteRecordInfo<'/Admin', '/Admin', Record<never, never>, Record<never, never>>,
    '/Assy': RouteRecordInfo<'/Assy', '/Assy', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/DowntimeRecords': RouteRecordInfo<'/DowntimeRecords', '/DowntimeRecords', Record<never, never>, Record<never, never>>,
    '/EHS': RouteRecordInfo<'/EHS', '/EHS', Record<never, never>, Record<never, never>>,
    '/Events': RouteRecordInfo<'/Events', '/Events', Record<never, never>, Record<never, never>>,
    '/Gmo': RouteRecordInfo<'/Gmo', '/Gmo', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/Maintenance': RouteRecordInfo<'/Maintenance', '/Maintenance', Record<never, never>, Record<never, never>>,
    '/MaintenanceMetrics': RouteRecordInfo<'/MaintenanceMetrics', '/MaintenanceMetrics', Record<never, never>, Record<never, never>>,
    '/Pcl': RouteRecordInfo<'/Pcl', '/Pcl', Record<never, never>, Record<never, never>>,
    '/PermissionManagement': RouteRecordInfo<'/PermissionManagement', '/PermissionManagement', Record<never, never>, Record<never, never>>,
    '/Qa_others': RouteRecordInfo<'/Qa_others', '/Qa_others', Record<never, never>, Record<never, never>>,
    '/Quality': RouteRecordInfo<'/Quality', '/Quality', Record<never, never>, Record<never, never>>,
    '/RouteManagement': RouteRecordInfo<'/RouteManagement', '/RouteManagement', Record<never, never>, Record<never, never>>,
  }
}
